name: Deploy VitePress site to Pages
# 在针对main分支的推送上运行。如果使用master分支作为默认分支，请将其更改为master
on:
  push:
    branches:
      - main
  # 允许你从Actions选项卡手动运行此工作流程
  workflow_dispatch:
# 设置GITHUB_TOKEN的权限，以允许部署到GitHub Pages
permissions:
  pages: write
  contents: read
# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: "pages"
  cancel-in-progress: true
runs-on: ubuntu-latest
steps:
  - name: Checkout
    uses: actions/checkout@v4
    fetch-depth: 0
  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: "lts/*"
    cache: npm
  - name: Install dependencies
    run: npm ci
  - name: Build with VitePress
    run: npm run docs:build
  - name: Deploy to GitHub Pages
    uses: actions/deploy-pages@v4